name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run plugin tests
      run: bundle exec rake spec:plugins

    - name: Run integration tests
      run: bundle exec rake spec:integration

    - name: Run all tests
      run: bundle exec rake spec

    - name: Build gem
      run: bundle exec rake build

  jekyll-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Test Jekyll build
      run: |
        bundle exec jekyll build --trace
      env:
        JEKYLL_ENV: test

    - name: Test Jekyll serve (dry run)
      run: |
        timeout 30s bundle exec jekyll serve --detach --port 4001 || true
        sleep 5
        if pgrep -f "jekyll serve"; then
          echo "Jekyll server started successfully"
          pkill -f "jekyll serve"
        else
          echo "Jekyll server failed to start"
          exit 1
        fi